### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by yanxinzju** [cdancette/rubi.bootstrap.pytorch#1]
hello
When I run python -m bootstrap.run -o rubi/options/vqacp2/rubi.yaml
there is a error
![image](https://user-images.githubusercontent.com/14920887/61184758-f9992280-a683-11e9-8bab-45fe1cd2bbd5.png)
I have downloaded extract_rcnn
 want to know if the data you provide is complete.
THANKS

**Comment by yanxinzju** [comment]
the error is 
No such file or directory: 'data/vqa/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36/COCO_train2014_000000325220.jpg.pth'

**Comment by yanxinzju** [comment]
OK，There was an error in the decompression. I have solved the problem.

**Comment by Cadene** [comment]
@yanxinzju Thanks for your interest and for having let us know that you solved the pb :)
