### ISSUE TITLE
No such file or directory:'logs/vqacp2/rubi/logs_rubi_val_oe.json'

### ISSUE THREAD

**Issue by BONiii1212** [cdancette/rubi.bootstrap.pytorch#12]
Hi,I have configured block.bootstrap.pytorch and bootstrap.pytorch. And I train Rubi model on VQA cp-2 dataset. The log folder is as follows, and there is no logs/vqacp2/rubi/ logs_rubi_val_oe.json
![QQ20210817-200323](https://user-images.githubusercontent.com/62984113/129724015-42bec7f5-26f1-4087-9f03-a5f123e9b2d6.png)
![QQ20210817-200348](https://user-images.githubusercontent.com/62984113/129724040-9a261888-11c5-4c4a-ad8d-6d68d8c4ef17.png)

**Comment by cdancette** [comment]
hi @BONiii1212, did you solve this issue ?
