### ISSUE TITLE
how to extract image features

### ISSUE THREAD

**Issue by ProbeTS** [cdancette/rubi.bootstrap.pytorch#13]
Could you please share the code to extract image features "2018-04-27_bottom-up-attention_fixed_36" or the pre-trained RCNN?

**Comment by cdancette** [comment]
You can download features here: wget http://data.lip6.fr/cadene/block/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36.tar

You can extract them using https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark
