### ISSUE TITLE
Object Labels

### ISSUE THREAD

**Issue by Soumya-dutta** [cdancette/rubi.bootstrap.pytorch#14]
I have downloaded the object features as specified. I need the object labels too for my work. Can you please point me to any such source

Thanks.

**Comment by cdancette** [comment]
Here are the object labels that correspond to the class in our features: http://webia.lip6.fr/~dancette/vgenome-features-object-vocab.txt

**Comment by Soumya-dutta** [comment]
Thanks for the vocab link. I believe the object indexing from the file starts from 1. Can you please let me know what the label 0 stands for?
