### ISSUE TITLE
Downloading features takes very long time

### ISSUE THREAD

**Issue by erobic** [cdancette/rubi.bootstrap.pytorch#3]
Hi,

```wget http://data.lip6.fr/cadene/block/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36.tar``` shows 2 days estimated time for download even though I have fairly high internet speed. Any chance you have the same file on a faster server?

**Comment by Cadene** [comment]
@erobic,
Thanks for your interest :)

You can download the features from AWS (we should push this soon):
https://github.com/Cadene/block.bootstrap.pytorch/issues/10

**Comment by erobic** [comment]
Thank you @Cadene  
It is super fast now!
