### ISSUE TITLE
Semantic tags corresponding to features

### ISSUE THREAD

**Issue by yanxinzju** [cdancette/rubi.bootstrap.pytorch#7]
I want to know the semantic tags corresponding to the detection feature.But only the index of the category is in the file.Can you provide the corresponding files of semantic tags and indexes?
THANKS

**Comment by cdancette** [comment]
@yanxinzju here is the file you requested

[objects_vocab.txt](https://github.com/cdancette/rubi.bootstrap.pytorch/files/6464256/objects_vocab.txt)
