### ISSUE TITLE
package requirement 'block.bootstrap.pytorch' is not satisfied

### ISSUE THREAD

**Issue by clytze0216** [cdancette/rubi.bootstrap.pytorch#9]
Thank you for sharing. I'm sorry that I'm new to VQA.
After the "pip install requirements.txt',Pycharm suggests"package requirement 'block.bootstrap.pytorch' is not satisfied", I check the pip list ,the block.bootstrap.pytorch has been installed and the version is 0.1.6, I dont know how to deal with this error, could you give some advice for me?
thanks a lot .I'm looking for your reply!

**Comment by cdancette** [comment]
It should be installable with pip. I cannot really help you, I suggest you create a new virtual environment and reinstall all packages.

Also, other repositories have been re-implementing rubi: 
https://github.com/antolu/RUBi, https://github.com/erobic/bias-mitigators, https://github.com/clovaai/rebias
